# Generated by Django 5.2.5 on 2025-12-03 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('cargo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sh_biblioteca.cargo',
            },
        ),
        migrations.CreateModel(
            name='EstadoUsuario',
            fields=[
                ('id_estado_usuario', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('estado_usuario', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'sh_biblioteca.estado_usuario',
            },
        ),
        migrations.CreateModel(
            name='GradoAcademico',
            fields=[
                ('id_grado_academico', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('grado_academico', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'sh_biblioteca.grado_academico',
            },
        ),
        migrations.CreateModel(
            name='ModalidadIngreso',
            fields=[
                ('id_modalidad_ingreso', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('modalidad_ingreso', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'sh_biblioteca.modalidad_ingreso',
            },
        ),
        migrations.CreateModel(
            name='PreRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(max_length=15, unique=True)),
                ('nombres', models.CharField(max_length=50)),
                ('paterno', models.CharField(blank=True, max_length=50)),
                ('materno', models.CharField(blank=True, max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('tipo_usuario', models.CharField(choices=[('U-01', 'Estudiante'), ('U-02', 'Docente'), ('U-04', 'Invitado')], max_length=4)),
                ('modalidad_ingreso', models.CharField(blank=True, choices=[('MIE-01', 'Prueba de Suficiencia Académica (PSA)'), ('MIE-02', 'Curso Preuniversitario (CPU)'), ('MIE-03', 'Examen de Dispensación (Excelencia Académica)'), ('MIE-04', 'Transferencia Externa'), ('MIE-05', 'Cambio de Carrera'), ('MIE-06', 'Convenios Especiales'), ('MIE-07', 'Titulados'), ('MID-08', 'Concurso de Méritos y Examen de Competencia'), ('MID-09', 'Interinato (Designación Temporal)'), ('MID-10', 'Contrato Docente'), ('MID-11', 'Titularización por Antigüedad'), ('MID-12', 'Designación Directa (Autoridades)')], max_length=6, null=True)),
                ('codigo_estudiante', models.CharField(blank=True, max_length=20, null=True)),
                ('grado_academico', models.CharField(blank=True, choices=[('GA-01', 'Primaria'), ('GA-02', 'Secundaria'), ('GA-03', 'Bachillerato'), ('GA-04', 'Técnico'), ('GA-05', 'Licenciatura'), ('GA-06', 'Maestría'), ('GA-07', 'Doctorado')], max_length=5, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('institucion', models.CharField(blank=True, max_length=100, null=True)),
                ('motivo_visita', models.CharField(blank=True, max_length=100, null=True)),
                ('duracion_estimada', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('aprobado', models.BooleanField(default=False)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'pre_registro',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id_sexo', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('sexo', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'sh_biblioteca.sexo',
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tipo_usuario', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('tipo_usuario', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'sh_biblioteca.tipo_usuario',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id_turno', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('turno', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'sh_biblioteca.turno',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('ci', models.CharField(max_length=15, unique=True)),
                ('nombres', models.CharField(max_length=50)),
                ('paterno', models.CharField(blank=True, max_length=50, null=True)),
                ('materno', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=30, null=True, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('id_sexo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sexo')),
            ],
            options={
                'db_table': 'sh_biblioteca.persona',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_contratacion', models.DateField()),
                ('id_cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cargo')),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.persona')),
                ('id_turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.turno')),
            ],
            options={
                'db_table': 'sh_biblioteca.empleado',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('id_estado_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.estadousuario')),
                ('id_grado_academico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.gradoacademico')),
                ('id_modalidad_ingreso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.modalidadingreso')),
                ('id_persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.persona')),
                ('id_tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipousuario')),
            ],
            options={
                'db_table': 'sh_biblioteca.usuario',
            },
        ),
    ]
