# Generated by Django 5.2.8 on 2025-12-03 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='estadousuario',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='gradoacademico',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='modalidadingreso',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='sexo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tipousuario',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='turno',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': False},
        ),
        migrations.RemoveField(
            model_name='preregistro',
            name='codigo_estudiante',
        ),
        migrations.RemoveField(
            model_name='preregistro',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='preregistro',
            name='duracion_estimada',
        ),
        migrations.RemoveField(
            model_name='preregistro',
            name='grado_academico',
        ),
        migrations.RemoveField(
            model_name='preregistro',
            name='institucion',
        ),
        migrations.RemoveField(
            model_name='preregistro',
            name='modalidad_ingreso',
        ),
        migrations.RemoveField(
            model_name='preregistro',
            name='motivo_visita',
        ),
        migrations.RemoveField(
            model_name='preregistro',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='preregistro',
            name='tipo_usuario',
        ),
        migrations.AddField(
            model_name='preregistro',
            name='id_grado_academico',
            field=models.CharField(blank=True, choices=[('GA-01', 'Primaria'), ('GA-02', 'Secundaria'), ('GA-03', 'Bachillerato'), ('GA-04', 'Técnico'), ('GA-05', 'Licenciatura'), ('GA-06', 'Maestría'), ('GA-07', 'Doctorado')], max_length=5, null=True, verbose_name='Grado Académico'),
        ),
        migrations.AddField(
            model_name='preregistro',
            name='id_modalidad_ingreso',
            field=models.CharField(blank=True, choices=[('MIE-01', 'Prueba de Suficiencia Académica (PSA)'), ('MIE-02', 'Curso Preuniversitario (CPU)'), ('MIE-03', 'Examen de Dispensación (Excelencia Académica)'), ('MIE-04', 'Transferencia Externa'), ('MIE-05', 'Cambio de Carrera'), ('MIE-06', 'Convenios Especiales'), ('MIE-07', 'Titulados'), ('MID-08', 'Concurso de Méritos y Examen de Competencia'), ('MID-09', 'Interinato (Designación Temporal)'), ('MID-10', 'Contrato Docente'), ('MID-11', 'Titularización por Antigüedad'), ('MID-12', 'Designación Directa (Autoridades)')], max_length=6, null=True, verbose_name='Modalidad de Ingreso'),
        ),
        migrations.AddField(
            model_name='preregistro',
            name='id_sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='M', max_length=2, verbose_name='Sexo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preregistro',
            name='id_tipo_usuario',
            field=models.CharField(choices=[('U-01', 'Estudiante'), ('U-02', 'Docente'), ('U-04', 'Invitado')], default='M', max_length=4, verbose_name='Tipo de Usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preregistro',
            name='ci',
            field=models.CharField(max_length=15, unique=True, verbose_name='Cédula de Identidad'),
        ),
        migrations.AlterField(
            model_name='preregistro',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='preregistro',
            name='email',
            field=models.EmailField(blank=True, max_length=30, null=True, unique=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='preregistro',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='preregistro',
            name='materno',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='preregistro',
            name='nombres',
            field=models.CharField(max_length=50, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='preregistro',
            name='paterno',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='preregistro',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono'),
        ),
    ]
