# Generated by Django 5.2.8 on 2025-12-03 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cargo_options_alter_empleado_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preregistro',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión'), ('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=10, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='preregistro',
            name='password',
            field=models.CharField(default='temp123', max_length=128, verbose_name='Contraseña'),
        ),
        migrations.AddField(
            model_name='preregistro',
            name='username',
            field=models.CharField(default='temp_user', max_length=30, unique=True, verbose_name='Nombre de Usuario'),
        ),
    ]
